README.md

.sln is incorrect in the readme, simple fix:)

Quick README change

---

src/client/component/bots.cpp
src/client/component/dedicated.cpp
src/client/component/fastfiles.cpp
src/client/component/gameplay.cpp
src/client/component/map_rotation.cpp
src/client/component/party.cpp
src/client/component/patches.cpp
src/client/component/stats.cpp
src/client/game/demonware/services/bdMarketing.cpp
src/client/game/demonware/services/bdMarketing.hpp
src/client/game/game.cpp
src/client/game/game.hpp
src/client/game/structs.hpp
src/client/game/symbols.hpp

Unlock everything and re-enable virtuallobby

---

src/client/component/logger.cpp
src/client/component/patches.cpp
src/client/game/structs.hpp

Logger now prints detailed LUI warnings etc.

Allow kbam while gamepad is enabled & Logger stuff

---

src/client/component/party.cpp

- fixes /map command on the same map disconnecting
- fixes disconnect with virtuallobby on

Minor fixes

---

src/client/component/discord.cpp

added discord presence (taken from iw6x open source) and got it working on S1x
- (line 49) cgArray does not exist on S1x, isnt added yet, or im using the wrong function. Because of this, partySize is not set.

add discord presence

---

src/client/component/discord.cpp

was off by 2 numbers somehow but i don't remember it ever messing up

discord presence - host name address

---

src/client/component/discord.cpp

got everything done with this now :p

discord presence final commit

---

src/client/component/dvars.cpp

I think this might have been a mistake

Fixed hooks in set dvars

---

src/client/component/dvars.cpp
src/client/component/dvars.hpp
src/client/game/symbols.hpp

I also decided to hook vector 3 for good measure. Tested on multiplayer and single player.
tested on single-player and multiplayer by printing vec3 arguments to confirm hook was successful.
Also minor misspelling of dvarName in symbols.hpp was corrected

I missed "flags" in vector 2 yesterday.

---

src/client/component/command.cpp

added filter to command listassetpool as requested by a person from discord.
tested on mp and the filter works as intended.
it seems discord doesn't display code formatting but on my visual studio code is well-formatted as I found it.

filter. (tested on mp)

---

src/client/component/party.cpp

/reconnect will not work unless you have at least joined one server. this should fix some issues/crashes

/reconnect changes

---

src/client/component/command.cpp

reverted to old if statement

---

src/client/component/virtuallobby.cpp

Don't patch virtuallobby if game isn't multiplayer

---

src/client/component/party.cpp

Shows the reason for kicking the player, so this should close #114

Show drop reason

---

src/client/component/game_console.cpp
src/client/component/party.cpp
src/client/component/rcon.cpp
src/client/component/videos.cpp

In case any of these char buffers should have their size changed in the future this should help to refactor.

Use sizeof operator more often

---

src/client/game/demonware/services/bdStorage.cpp

improved motd for zombies

---

src/client/component/command.cpp

Added the notarget command for SP & MP.

Notarget command

---

src/client/component/patches.cpp
src/client/component/ui_scripting.cpp
src/client/component/ui_scripting.hpp
src/client/game/structs.hpp
src/client/game/symbols.hpp
src/client/game/ui_scripting/execution.cpp
src/client/game/ui_scripting/execution.hpp
src/client/game/ui_scripting/lua/context.cpp
src/client/game/ui_scripting/lua/context.hpp
src/client/game/ui_scripting/lua/engine.cpp
src/client/game/ui_scripting/lua/engine.hpp
src/client/game/ui_scripting/lua/error.cpp
src/client/game/ui_scripting/lua/error.hpp
src/client/game/ui_scripting/lua/scheduler.cpp
src/client/game/ui_scripting/lua/scheduler.hpp
src/client/game/ui_scripting/lua/value_conversion.cpp
src/client/game/ui_scripting/lua/value_conversion.hpp
src/client/game/ui_scripting/script_value.cpp
src/client/game/ui_scripting/script_value.hpp
src/client/game/ui_scripting/stack_isolation.cpp
src/client/game/ui_scripting/stack_isolation.hpp
src/client/game/ui_scripting/types.cpp
src/client/game/ui_scripting/types.hpp

Example script: https://codeshare.io/K866D7

Bring over LUI stuff from iw6x

---

src/client/game/ui_scripting/lua/engine.cpp

i assume you meant this when copying changes from lua scripting to ui scripting

/scripts -> /ui_scripts ?

---

src/client/component/auth.cpp
src/client/component/network.cpp

`msg->cursize - offset` could be negative, which will cause a crash

Check msg size in command handling

---

data/ui_scripts/server_list/__init__.lua

changed require to include this change was also needed for when fed did the new fps and ping overlay in lua

fix server list lua not loading

---

data/ui_scripts/scoreboard/__init__.lua

Show numerical ping in scoreboard

---

src/client/component/gameplay.cpp
src/client/game/dvars.cpp
src/client/game/dvars.hpp
src/client/game/structs.hpp

Could not finish struct trace_t

Port elevators patch from iw6x

---

src/client/component/auth.cpp
src/client/component/bots.cpp
src/client/component/branding.cpp
src/client/component/command.cpp
src/client/component/command.hpp
src/client/component/dvar_cheats.cpp
src/client/component/game_console.cpp
src/client/component/gameplay.cpp
src/client/component/logfile.cpp
src/client/component/map_rotation.cpp
src/client/component/network.cpp
src/client/component/patches.cpp
src/client/game/dvars.cpp
src/client/game/dvars.hpp
src/client/game/structs.hpp
src/client/game/symbols.hpp

Closes #113
Things I wanted to note
From the assembly code it's possible to confirm there is only one char argument being passed to client command function.
If there was a second parameter it would not make sense because it's not being used anywhere in the game's function.
Also I think it's a bad copy paste because only on sp version of client command there is a second parameter to client command func.
MP always had one but for some reason on S1 it's now a char instead of an int

Add g_speed, jump_height & ladderpushvel

---

src/client/game/scripting/lua/context.cpp

Adds several overloads. Credits to fed

Enhance vector in lua scripts

---

deps/extra/gsc-tool/interface.cpp
deps/extra/gsc-tool/interface.hpp
src/client/component/gsc/script_loading.cpp

Original commit (I made a couple of changes so the patch is better suited for s1x):
https://github.com/fedddddd/h2-mod/commit/d3af34572d570b559f1882f0f5da2d48148b0eb8

GSC: Allow custom scripts to include stock scriptfiles

---

src/client/game/ui_scripting/script_value.hpp
src/client/game/ui_scripting/types.cpp
src/client/game/ui_scripting/types.hpp

Removed some unnecessary ../../ as well from some includes directives because I heard from some guy in the Microsoft/STL discord that they are bad. Basically, to my understanding, they don't let the compiler check properly if you can actually include the file so I fixed that.

Fix format and remove anon namespace from header

---

src/client/component/gsc/script_loading.cpp

H1 did this and I am thankful for their patch

gsc: Stop loading create art fake gsc files

---

src/client/component/gsc/script_loading.cpp

gsc: Better patch for fake rawfiles

---

.gitmodules

Forgot to do this the other day

Update git modules

---

src/client/component/branding.cpp
src/client/component/dedicated.cpp
src/client/component/dvars.cpp
src/client/component/dvars.hpp
src/client/component/filesystem.cpp
src/client/component/network.cpp
src/client/component/patches.cpp
src/client/component/ranked.cpp

remove description because it unused + destroys original dvar description

refactor(dvars): use our code style

---

src/common/utils/memory.cpp

https://en.cppreference.com/w/cpp/memory/c/free

refactor(memory): remove nullptr check before std::free

---

data/ui_scripts/patches/__init__.lua

fix gamemode in the ui

---

src/client/component/bullet.cpp
src/client/game/dvars.cpp
src/client/game/dvars.hpp

also see my other pr in game/dvars.cpp and game/dvars.cpp

add increased bullet penetration dvar
